# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_country', models.CharField(max_length=3)),
                ('name_country', models.CharField(max_length=45)),
                ('code_phone', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
    ]
