# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idiom', '0001_initial'),
        ('rol', '0001_initial'),
        ('theme', '0001_initial'),
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=45, unique=True)),
                ('first_name', models.CharField(db_column='firstName', max_length=45)),
                ('middle_name', models.CharField(blank=True, db_column='middleName', max_length=45, null=True)),
                ('last_name', models.CharField(db_column='lastName', max_length=45)),
                ('mothers_name', models.CharField(blank=True, db_column='mothersName', max_length=45, null=True)),
                ('password', models.CharField(max_length=45)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('mail', models.CharField(blank=True, max_length=45, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('fk_country', models.ForeignKey(db_column='fk_country', on_delete=django.db.models.deletion.DO_NOTHING, to='country.Country')),
                ('fk_idiom', models.ForeignKey(db_column='fk_idiom', on_delete=django.db.models.deletion.DO_NOTHING, to='idiom.Idiom')),
                ('fk_rol', models.ForeignKey(db_column='fk_rol', on_delete=django.db.models.deletion.CASCADE, to='rol.Rol')),
                ('fk_theme', models.ForeignKey(db_column='fk_theme', on_delete=django.db.models.deletion.DO_NOTHING, to='theme.Theme')),
            ],
        ),
    ]
