# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_menu', models.CharField(max_length=3)),
                ('name_menu', models.CharField(max_length=45)),
                ('des_menu', models.TextField(blank=True, null=True)),
                ('url_menu', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'permission',
                'managed': False,
            },
        ),
    ]
